config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'chat/:id' => 'chats#show', as: 'chat'
  post 'chat/create/:id' => 'chats#create', as: 'chat_create'
  resources :notifications, only: [:index]

  get 'users/register' => 'users#register', as: 'user_register'
  get 'users/matched' => 'users#matched', as: 'user_matched'
  get 'users/show' => 'users#show', as: 'user'
  get 'users/search' => 'users#search', as: 'search'
  post 'users/result' => 'users#result', as: 'result'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users, only: [:index, :edit, :update, :destroy]

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'follow/search/:id' => 'relationships#follow_search', as: 'follow_search'
  get 'skip/:id' => 'relationships#skip', as: 'skip'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  belongs_to :genre, optional: true
  enum gender: { 未選択:0, 男性:1, 女性:2}
  has_many :user_rooms
  has_many :chats
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin

  def index
    @users = User.page(params[:page]).per(10).where.not(admin: true)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_path
  end

  private

  def if_not_admin
    redirect_to user_path unless current_user.admin?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_register_path
  end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     user_register_path
   end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    users = User.where(genre_id: current_user.genre_id).where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    current_user.now = 0 #current_userが現在見ているページをリセット
    current_user.save
    @user = users[current_user.now]
  end

  def register
    @user = User.find(current_user.id)
  end

  def update
    user = User.find(current_user.id)
    if user.update(user_params)
      redirect_to  user_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def matched
    @users = current_user.following_user & current_user.follower_user
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(12)
  end

  def destroy
    user = User.find(current_user.id)
    user.destroy
    redirect_to root_path
  end

  def search
    @users = User.all.where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(6)
  end

  def result
    search_user = User.new(search_params)
    if search_user.gender == "未選択"
      selected_gender = User.all.where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    elsif search_user.gender == "男性"
      selected_gender = User.where(gender: "男性").where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    else
      selected_gender = User.where(gender: "女性").where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    end
    selected_genre = User.where(genre: search_user.genre).where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    @users = selected_gender & selected_genre
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(6)
  end

  private

  def user_params
    params.require(:user).permit(:genre_id,:name,:image,:gender,:introduction)
  end

  def search_params
    params.permit(:genre_id,:gender)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% unless current_user.following?(user) %>
  <%= link_to follow_search_path(user.id), method: :POST, class: "btn btn-lg btn-outline-danger fw-bold  bg-transparent ", remote: true do %>
    <i class="fas fa-heart" style="color: red"></i>
  <% end %>
<% end %>

app/views/users/_result.html.erb
    <% if users.any? %>
      <div class="row">
        <% users.each do |user| %>
            <div class="col-xl-2 col-lg-4">
              <%= attachment_image_tag user, :image,  format: 'image', size: "200x200", fallback: "no_image.png", class: "img" %>
              <table align="center">
                <tbody>
                  <tr>
                    <td><%= user.name %></td>
                  </tr>
                  <tr>
                    <td><%= user.gender %></td>
                  </tr>
                  <tr>
                    <% if user.genre.nil? %>
                      <td>未設定</td>
                    <% else %>
                      <td><%= user.genre.name %></td>
                    <% end %>
                  </tr>
                </tbody>
              </table>
              <div id="follow-<%= user.id %>">
                <%= render "follow", user: user %>
              </div>
            </div>
        <% end %>
      </div>
    <% else %>
      条件に合ったユーザーが見つかりません。
    <% end %>
    <%= paginate @users %>

app/views/users/_slide.html.erb
<% if user.nil? %>
条件にマッチするユーザーが見つかりません</br>
他のゲームのユーザーを探す場合はゲームタグを変更してください。
<% else %>
<div>
  <%= link_to follow_path(user.id), method: :POST, class: "btn btn-lg btn-outline-danger fw-bold  bg-transparent mb-3 mr-5", remote: true do %>
    <i class="fas fa-heart" style="color: red"></i>
  <% end %>
    <%= link_to skip_path(user.id), class: "btn btn-lg btn-outline-light fw-bold border-white bg-transparent mb-3 ml-5", remote: true do %>
    <i class="fas fa-forward"></i>
  <% end %>
</div>
<%= attachment_image_tag user, :image,  format: 'image', size: "400x400", fallback: "no_image.png", class: "img" %>
<h1><%= user.name %></h1>
<div><%= simple_format(h(user.introduction)) %></div>
<% end %>

app/views/users/edit.html.erb
<div>
  <h2>プロフィール編集</h2>

  <%= form_with model: @user, local: true do |f| %>

    <div class="field">
      <%= f.label :name, "ニックネーム" %><br />
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field">
      <%= f.label "性別" %><br />
      <%= f.radio_button :gender, :男性 %>
      <%= f.label :gender, "男性", class: "display: inline-block" %>
      <%= f.radio_button :gender, :女性 %>
      <%= f.label :gender, "女性", class: "display: inline-block" %>
    </div>

    <div class="field">
      <%= f.label "プロフィール画像" %><br />
      <%= f.attachment_field :image %>
    </div>

    <div class="field">
      <%= f.label "プレイ中のゲーム" %><br />
      <%= f.collection_select(:genre_id, Genre.all.order("name"), :id, :name, {prompt: "選択してください"}) %>
    </div>

    <div class="field">
      <%= f.label "自己紹介" %><br />
      <%= f.text_area :introduction %>
    </div>

    <div><%= f.submit "更新する", class: "btn btn-lg btn-secondary fw-bold border-white bg-white mt-3 mb-5" %></div>

  <% end %>
  <%= link_to '退会する', user_path(current_user.id), method: :DELETE, data: { confirm: "ユーザー情報は削除されます。本当に退会しますか？" }, class: "btn btn-lg btn-secondary fw-bold border-white bg-white mt-5" %>
</div>

app/views/users/index.html.erb
<div class="user">
<%= render 'slide', user: @user %>
</div>

app/views/users/match.html.erb
<% current_user.following_user && current_user.follower_user.where.not(id: current_user.id).each do |user| %>
<%= attachment_image_tag user, :image,  format: 'image', size: "300x300" %>
<table>
  <tbody>
    <tr>
      <td>ニックネーム</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>性別</td>
      <td><%= user.gender %></td>
    </tr>
    <tr>
      <td>プレイしているゲーム</td>
      <td><%= user.genre.name %></td>
    </tr>
    <tr>
      <td>自己紹介</td>
      <td><%= user.introduction %></td>
    </tr>
    <tr>
      <td><%= link_to "チャットルーム", chat_path(user.id)%></td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/users/matched.html.erb
<div>
    <% if @users.any? %>
      <div class="row">
        <% @users.each do |user| %>
            <div class="col-2">
              <div><%= attachment_image_tag user, :image,  format: 'image', size: "200x200", fallback: "no_image.png", class: "img" %>
                <table align="center">
                  <tbody>
                    <tr>
                      <td><%= user.name %></td>
                    </tr>
                    <tr>
                      <td><%= user.gender %></td>
                    </tr>
                    <tr>
                      <td><%= user.genre.name %></td>
                    </tr>
                  </tbody>
                </table>
                <%= link_to "メッセージ", chat_path(user.id), class: "btn btn-lg btn-secondary fw-bold border-white bg-white" %>
              </div>
            </div>
        <% end %>
      </div>
    <% else %>
      フレンドが見つかりません
    <% end %>
<%= paginate @users %>
</div>

app/views/users/register.html.erb
<h2>プロフィールを入力してください。</h2>
<%= form_with model: @user, local: true do |f| %>
  <div class="field">
    <%= f.label :name, "ニックネーム" %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label "性別" %><br />
    <%= f.radio_button :gender, :男性 %>
    <%= f.label :gender, "男性", class: "display: inline-block" %>
    <%= f.radio_button :gender, :女性 %>
    <%= f.label :gender, "女性", class: "display: inline-block" %>
  </div>

  <div class="field">
    <%= f.label "プロフィール画像" %><br />
    <%= f.attachment_field :image %>
  </div>

  <div class="field">
    <%= f.label "プレイ中のゲーム" %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name ) %>
  </div>

  <div class="field">
    <%= f.label "自己紹介" %><br />
    <%= f.text_area :introduction %>
  </div>

  <div><%= f.submit "登録", class: "btn btn-lg btn-secondary fw-bold border-white bg-white" %></div>

<% end %>

app/views/users/result.js.erb
$(".users").html("<%= j(render 'users/result',  users: @users ) %>")

app/views/users/search.html.erb
<h2>探したいユーザーの情報を選択してください。</h2>
<%= form_with url: result_path, remote: true do |f| %>
  <table align="center">
    <thead>
      <tr>
        <td><%= f.label "ゲーム" %></td>
        <td><%= f.collection_select(:genre_id, Genre.all, :id, :name ) %></td>
      </tr>
      <tr>
        <td><%= f.label "性別" %></td>
        <td>
          <%= f.radio_button :gender, :未選択 %>
          <%= f.label :gender, "未選択", class: "display: inline-block" %>
          <%= f.radio_button :gender, :男性 %>
          <%= f.label :gender, "男性", class: "display: inline-block" %>
          <%= f.radio_button :gender, :女性 %>
          <%= f.label :gender, "女性", class: "display: inline-block" %>
        </td>
      </tr>
    </thead>
  </table>

  <div><%= f.submit "検索", class: "btn btn-lg btn-secondary fw-bold border-white bg-white" %></div>

<% end %>
<div class="users">
<%= render 'result', users: @users %>
</div>

app/views/users/show.html.erb
<div>
<%= attachment_image_tag current_user, :image,  format: 'image', size: "400x400", fallback: "no_image.png", class: "img" %>
<table align="center">
  <tbody>
    <tr>
      <td style="width: 50%">ニックネーム</td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
      <td>性別</td>
      <td><%= current_user.gender %></td>
    </tr>
    <tr>
      <td>登録されているゲーム</td>
      <td><%= current_user.genre.name %></td>
    </tr>
    <tr>
      <td>自己紹介</td>
      <td><%= simple_format(h(current_user.introduction)) %></td>
    </tr>
  </tbody>
</table>
<%= link_to "編集する", edit_user_path(current_user.id), class: "btn btn-lg btn-secondary fw-bold border-white bg-white mt-3" %>
</div>