config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'chat/:id' => 'chats#show', as: 'chat'
  post 'chat/create/:id' => 'chats#create', as: 'chat_create'
  resources :notifications, only: [:index]

  get 'users/register' => 'users#register', as: 'user_register'
  get 'users/matched' => 'users#matched', as: 'user_matched'
  get 'users/show' => 'users#show', as: 'user'
  get 'users/search' => 'users#search', as: 'search'
  post 'users/result' => 'users#result', as: 'result'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users, only: [:index, :edit, :update, :destroy]

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'follow/search/:id' => 'relationships#follow_search', as: 'follow_search'
  get 'skip/:id' => 'relationships#skip', as: 'skip'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :users
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :if_not_admin

  def index
     @genres = Genre.page(params[:page]).per(10).order("name")
     @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def if_not_admin
    redirect_to user_path unless current_user.admin?
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/index.html.erb
<div>
<h2>ゲームジャンル管理</h2>
<%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "追加する" %>
<% end %>
<table align="center">
  <thead>
    <td>ジャンル名</td>
    <td></td>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to "削除する", admin_genre_path(genre.id), method: :delete, class: "btn btn-sm btn-secondary fw-bold border-white bg-white" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div><%= paginate @genres %></div>
</div>