config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'chat/:id' => 'chats#show', as: 'chat'
  post 'chat/create/:id' => 'chats#create', as: 'chat_create'
  resources :notifications, only: [:index]

  get 'users/register' => 'users#register', as: 'user_register'
  get 'users/matched' => 'users#matched', as: 'user_matched'
  get 'users/show' => 'users#show', as: 'user'
  get 'users/search' => 'users#search', as: 'search'
  post 'users/result' => 'users#result', as: 'result'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users, only: [:index, :edit, :update, :destroy]

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'follow/search/:id' => 'relationships#follow_search', as: 'follow_search'
  get 'skip/:id' => 'relationships#skip', as: 'skip'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true
  validates :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.name = current_user.name
    @contact.email = current_user.email
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to new_contact_path
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact)
          .permit(:title,:message )
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<table>
  <tbody>
    <tr>
      <td class="text-right"style="width: 30%;">お名前:</td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
      <td class="text-right">メールアドレス:</td>
      <td><%= current_user.email %></td>
    </tr>
    <tr>
      <td class="text-right">件名:</td>
      <td><%= @contact.title %></td>
    </tr>
    <tr>
      <td class="text-right">内容:</td>
      <td><%= simple_format(h(@contact.message)) %></td>
    </tr>
  </tbody>
</table>
<div>
<%= form_for(@contact) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :message %>
  <div><%= f.submit '送信',class: "btn btn-lg btn-secondary fw-bold border-white bg-white" %></div>
<% end %>
<%= form_for @contact, url: back_path do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :message %>
  <div class="mt-3"><%= f.submit '入力画面に戻る',class: "btn btn-lg btn-secondary fw-bold border-white bg-white" %></div>
<% end %>
</div>

app/views/contacts/new.html.erb
<div>
<%= form_for(@contact, url: confirm_path) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :title, '件名(必須)' %>
    <%= f.text_field :title, class: 'form-control col-md-4 offset-md-4' %>
  </div>

  <div class="form-group">
    <%= f.label :message, '内容(必須)' %>
    <%= f.text_area :message, size: '10x10', class: 'form-control col-md-6 offset-md-3' %>
  </div>

  <div>
    <%= f.submit '入力内容確認', class: "btn btn-lg btn-secondary fw-bold border-white bg-white" %>
  </div>
<% end %>
</div>