config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'chat/:id' => 'chats#show', as: 'chat'
  post 'chat/create/:id' => 'chats#create', as: 'chat_create'
  resources :notifications, only: [:index]

  get 'users/register' => 'users#register', as: 'user_register'
  get 'users/matched' => 'users#matched', as: 'user_matched'
  get 'users/show' => 'users#show', as: 'user'
  get 'users/search' => 'users#search', as: 'search'
  post 'users/result' => 'users#result', as: 'result'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users, only: [:index, :edit, :update, :destroy]

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'

  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :genres, only: [:index, :create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'follow/search/:id' => 'relationships#follow_search', as: 'follow_search'
  get 'skip/:id' => 'relationships#skip', as: 'skip'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :notifications, dependent: :destroy
  validates :message, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :title, presence: true
  validates :message, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :users
  validates :name, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  belongs_to :genre, optional: true
  enum gender: { 未選択:0, 男性:1, 女性:2}
  has_many :user_rooms
  has_many :chats
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def following?(user)
    following_user.include?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats.order(id: "DESC")
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    chat = current_user.chats.new(chat_params)
    chat.save
    old_notification = Notification.where(visitor_id: current_user.id, visited_id: params[:id], action: "chat")
    if old_notification.any?
      old_notification.destroy_all #同じ組み合わせの古い通知レコードは削除
    end
    notification = current_user.active_notifications.new(chat_id: chat.id, visited_id: params[:id], action: "chat")
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
    @room = user_rooms.room
    @chats = @room.chats.order(id: "DESC")
    @chat = Chat.new(room_id: @room.id)
  end

  private

  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new
    end
  end

  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.name = current_user.name
    @contact.email = current_user.email
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to new_contact_path
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact)
          .permit(:title,:message )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    users = User.where(genre_id: current_user.genre_id).where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    current_user.now = 0 #current_userが現在見ているページをリセット
    current_user.save
    @user = users[current_user.now]
  end

  def register
    @user = User.find(current_user.id)
  end

  def update
    user = User.find(current_user.id)
    if user.update(user_params)
      redirect_to  user_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def matched
    @users = current_user.following_user & current_user.follower_user
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(12)
  end

  def destroy
    user = User.find(current_user.id)
    user.destroy
    redirect_to root_path
  end

  def search
    @users = User.all.where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(6)
  end

  def result
    search_user = User.new(search_params)
    if search_user.gender == "未選択"
      selected_gender = User.all.where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    elsif search_user.gender == "男性"
      selected_gender = User.where(gender: "男性").where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    else
      selected_gender = User.where(gender: "女性").where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    end
    selected_genre = User.where(genre: search_user.genre).where.not(id: current_user.id).where.not(admin: true).where.not(id: current_user.following_user).order("updated_at DESC")
    @users = selected_gender & selected_genre
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(6)
  end

  private

  def user_params
    params.require(:user).permit(:genre_id,:name,:image,:gender,:introduction)
  end

  def search_params
    params.permit(:genre_id,:gender)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
      @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error">
      <% model.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="generator" content="">

    <title>eFriends</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1f23f80937.js" crossorigin="anonymous"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="d-flex h-100 text-center text-white bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <% if user_signed_in? %>
            <h3 class="float-md-start mb-0 "><%= link_to "eFriends", users_path, class: "title" %></h3>
          <% else %>
            <h3 class="float-md-start mb-0 "><%= link_to "eFriends", root_path, class: "title" %></h3>
          <% end %>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <% if user_signed_in? %>
              <% if current_user.admin %>
                <%= link_to "ユーザー管理", admin_users_path, class: "nav-link"%>
                <%= link_to "ジャンル管理", admin_genres_path, class: "nav-link" %>
              <% else %>
                <%= link_to "探す", users_path, class: "nav-link" %>
                <% if unchecked_notifications.any? %>
                  <i class="fa fa-circle circle"></i>
                <% end %>
                <%= link_to "お知らせ", notifications_path, class: "nav-link" %>
                <%= link_to "フレンド", user_matched_path, class: "nav-link" %>
                <%= link_to "検索", search_path, class: "nav-link" %>
                <%= link_to "マイページ", user_path, class: "nav-link" %>
                <%= link_to "お問い合わせ", new_contact_path, class: "nav-link" %>
              <% end %>
              <%= link_to "ログアウト", destroy_user_session_path, class: "nav-link", method: :delete %>
            <% else %>
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            <% end %>
          </nav>
        </div>
      </header>
      <%= yield %>
      <footer class="mt-auto text-white-50">
        <p>Copyright © eFriends Inc. All Rights Reserved.</p>
      </footer>
    </div>
  </body>
</html>